### ISSUE TITLE
Update main entrypoint to accept input URL and output path arguments

### ISSUE THREAD

**Issue by agmangas** [baeda-polito/matrix-profile#1]
Update the main entrypoint so it can receive two arguments:

* The `input` dataset via an HTTP URL. The tool should then download the dataset from that URL; since it's a [presigned URL](https://docs.aws.amazon.com/AmazonS3/latest/userguide/ShareObjectPreSignedURL.html), the tool would not need to deal with authentication—it can just download the dataset directly.
* The local path to the `output` HTML report. The platform would then get that HTML report and upload it to the object storage service for the user to review later.

For example:

```console
$ python -m src.cmp.main --input https://presigned-download-url.com --output /tmp/output.html
⬇️ Downloading file from https://presigned-download-url.com
... [Execution logs] ... 
🎉 Report generated sucessfully on /tmp/output.html
```

If the tool fails for any reason, the platform would capture the error output and present it to the user. The following is an example of how the tool could show the errors:

```console
$ python -m src.cmp.main --input https://presigned-download-url.com --output /tmp/output.html
🔴 The execution failed due to the following reasons:
* Reason 1
* Reason 2
* ...
```

**Comment by RobertoChiosa** [comment]
Added input and output using argparse library and tested
