### ISSUE TITLE
Create a fork to mirror repository in MODERATE's GitHub organization

### ISSUE THREAD

**Issue by agmangas** [baeda-polito/matrix-profile#2]
It would be nice if we could create a fork to mirror this repository in [MODERATE's GitHub organization](https://github.com/MODERATE-Project). That way, all the software projects of MODERATE would be available in the same catalogue, which would be much simpler for external users.

For example, we have already done something similar with LINKS' [Cybersecurity-LINKS/trust-service](https://github.com/Cybersecurity-LINKS/trust-service), which has been forked into its own repository [MODERATE-Project/trust-service](https://github.com/MODERATE-Project/trust-service).

Furthermore, this would greatly simplify integration with the Continuous Integration pipeline that builds the Docker images and publishes them to MODERATE's private registry.

**Comment by RobertoChiosa** [comment]
How would you proceed on this aspect? 
Do we need a final version of our code and then fork it in Moderate repository?

**Comment by agmangas** [comment]
If it's OK with you, I can fork this repository into the [MODERATE-Project](https://github.com/MODERATE-Project) organization and contribute the source code to build the Docker images and push them to MODERATE's artifact registry. So, nothing you need to worry about from your side. I'd just like your approval, and if any issues arise, I may ask for your help debugging them.

For example, we've done something similar with LINKS' trust services: https://github.com/MODERATE-Project/trust-service

**Comment by RobertoChiosa** [comment]
As sonn as i will be ready I will give you a GO

**Comment by agmangas** [comment]
Thank you for your response Roberto!

Do you mean that you need to push further updates to this repository before I fork it to the MODERATE-Project organization? If so, I can go ahead and fork the project now, and we can merge your updates into the new repository later, whenever they’re ready (no rush). GitHub makes that process very simple. Would that work for you?

**Comment by RobertoChiosa** [comment]
Well if we can sync the two projects without much effort, you can do it right now and eventually we can sync them later if necessary. You can proceed 😃

**Comment by agmangas** [comment]
We've already created the fork in MODERATE's GitHub organization:

https://github.com/MODERATE-Project/matrix-profile

I’ve also added a new GitHub Actions file to publish the package to PyPI, and version 1.0.1 is now available in PyPI:

https://pypi.org/project/moderate-matrix-profile/

However, the original package name `cmp` conflicts with an existing package on PyPI. As a result, I [had to rename the package](https://github.com/MODERATE-Project/matrix-profile/commit/10d01ca610b7f411345f09869b98a520829e389f) from `cmp` to `moderate-matrix-profile`. You'll see that, although I appear as the maintainer, you are listed as the original author, as it should be 🙂

That said, I don't want to impose this change on you, so feel free to keep the original name if you prefer. Having the package published on PyPI is simply meant to make our lives easier when deploying it to the MODERATE platform.

**Comment by RobertoChiosa** [comment]
From our side no problem in terms of package renaming 😃
Great Job
