### ISSUE TITLE
Create documentation for basic tool usage

### ISSUE THREAD

**Issue by agmangas** [baeda-polito/matrix-profile#3]
We should write documentation so that end users who are not familiar with the tool can learn the basic concepts to use it. For example:

* What does the tool do?
* What's the main interface of the tool?
* What are the accepted input dataset formats? What columns should be included? What's the minimum time series interval for the tool to function?

The documentation could be added to the current repository as Markdown files. We would then copy it to the [MODERATE Documentation](https://github.com/MODERATE-Project/moderate-docs) site. Another option would be to push it directly to MODERATE's documentation repository.

**Comment by RobertoChiosa** [comment]
Documentation done in dev branch, it will be online in the next patch release
